# Generated by Django 4.2.13 on 2024-07-03 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('start_bid', models.FloatField()),
                ('image_url', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=64)),
                ('active_status', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
