# Generated by Django 5.0.3 on 2024-10-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='restaurant',
        ),
    ]
