# Generated by Django 5.0.3 on 2024-10-24 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_menucategory_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.restaurant'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
    ]
