# Generated by Django 5.0.3 on 2024-10-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menucategory_restaurant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='item_name',
        ),
    ]
