# Generated by Django 5.0.3 on 2024-11-16 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='orders.chain'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
