# Generated by Django 5.0.3 on 2024-12-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_cancellation_notes_alter_restaurant_chain_and_more'),
    ]

    operations = [
    ]
