# Generated by Django 5.1.4 on 2024-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_menuitem_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
